version: '2.2'
services:
    web_analyzer:
        image: nginx
        restart: always
        volumes:
            - ../src/analyzer:/usr/share/nginx/html
        ports:
            - 80:80
    msg_handler:
        build: message_handler/
        restart: always
        volumes:
            - ../src/message_handler:/code
        depends_on:
            - rabbitmq
            - datamanager
        links:
            - rabbitmq
        environment: # TODO groups of environment vars if possible
            - RABBIT_USER=message_handler
            - RABBIT_PASS=somepass
    rabbitmq:
        build: rabbitmq/
        restart: always
        environment:
            - RABBITMQ_LOGS=/var/log/rabbitmq/rabbit1.log
            - RABBITMQ_SASL_LOGS=/var/log/rabbit2.log
        ports:
            - 15678:15672
            - 5678:5672
    bastion:
        build: bastion_node/
        volumes:
            - ../:/code
        links:
            - rabbitmq
            - msg_handler
            - web_analyzer
        depends_on:
            - msg_handler
            - scanner
        environment:
            - RABBIT_USER=root
            - RABBIT_PASS=toor

    scanner:
        build: scanner/
        restart: always
        volumes:
            - ../src/scanner:/code
        scale: 3
        # Limit container resources
        cpus: 0.15 # < 5% of host CPU time
        mem_limit: 128m # < 128MB of host RAM
        memswap_limit: 128m # do not allow swap (https://docs.docker.com/engine/admin/resource_constraints/#--memory-swap-details)
        depends_on: 
            - msg_handler

    datamanager:
        build:
            context: .
            dockerfile: ./datamanager/Dockerfile
            args:
                - WILDFLY_ADMIN=root
                - WILDFLY_PASSWORD=toor
                # - USER=$USER
        restart: always
        volumes:
            - ../src/datamanager/datamanager-ear:/code/
        ports:
            - 8080:8080
            - 9990:9990

    replicamanager:
        build:
            context: .
            dockerfile: ./replicamanager/Dockerfile
            args:
                - WILDFLY_ADMIN=root
                - WILDFLY_PASSWORD=toor
        restart: always
        depends_on: 
                - datamanager
        scale: 5
        volumes:
            - ../src/replicamanager/replicamanager-ear:/code

### Volumes and networking

