version: '2'
services:
###
    web_analyzer:
        image: nginx
        restart: always
        volumes:
            - ../public_html:/usr/share/nginx/html
        ports:
            - 80:80
    msg_handler:
        build: message_handler/
        restart: always
        volumes:
            - ../src/message_handler:/code
        depends_on:
            - rabbitmq
        links:
            - rabbitmq
        environment: # TODO groups of environment vars if possible
            - RABBIT_USER=root
            - RABBIT_PASS=toor
    rabbitmq:
        image: rabbitmq:3-management
        restart: always
        environment:
            - RABBITMQ_DEFAULT_USER=root
            - RABBITMQ_DEFAULT_PASS=toor
        volumes:
            - ds_rabbitmq_home:/var/lib/rabbitmq
        ports:
            - 15672:15672
            - 5672:5672
    bastion:
        build: bastion_node/
        volumes:
            - ../:/code
        links:
            - rabbitmq
            - msg_handler
            - web_analyzer
        environment:
            - RABBIT_USER=root
            - RABBIT_PASS=toor

###



### Volumes and networking
volumes: ## TODO read about the differences with the other way of volumes definition
    ds_rabbitmq_home:

