version: '2.2'
services:
###
    web_analyzer:
        image: nginx
        restart: always
        volumes:
            - ../public_html:/usr/share/nginx/html
        ports:
            - 80:80
    msg_handler:
        build: message_handler/
        restart: always
        volumes:
            - ../src/message_handler:/code
        depends_on:
            - rabbitmq
        links:
            - rabbitmq
            - datamanager
        environment: # TODO groups of environment vars if possible
            - RABBIT_USER=root
            - RABBIT_PASS=toor
    rabbitmq:
        image: rabbitmq:3-management
        restart: always
        environment:
            - RABBITMQ_DEFAULT_USER=root
            - RABBITMQ_DEFAULT_PASS=toor
        volumes:
            - ds_rabbitmq_home:/var/lib/rabbitmq
        ports:
            - 15672:15672
            - 5672:5672
    bastion:
        build: bastion_node/
        volumes:
            - ../:/code
        links:
            - rabbitmq
            - msg_handler
            - web_analyzer
        environment:
            - RABBIT_USER=root
            - RABBIT_PASS=toor

    scanner:
        build: scanner/
        restart: always
        volumes:
            - ../src/scanner:/code
        environment:
            - RABBIT_USER=root
            - RABBIT_PASS=toor
        depends_on:
            - rabbitmq
        links:
            - rabbitmq
        # Limit container resources
        cpus: 0.05 # < 5% of host CPU time
        mem_limit: 128m # < 128MB of host RAM
        memswap_limit: 128m # do not allow swap (https://docs.docker.com/engine/admin/resource_constraints/#--memory-swap-details)

    datamanager:
        build:
            context: .
            dockerfile: ./datamanager/Dockerfile
            args:
                - WILDFLY_ADMIN=root
                - WILDFLY_PASSWORD=toor
                # - USER=$USER
        restart: always
        volumes:
            - ../src/datamanager/build:/opt/jboss/wildfly/standalone/deployments
        ports:
            - 8080:8080
            - 9990:9990

    replicamanager:
        build:
            context: .
            dockerfile: ./replicamanager/Dockerfile
            args:
                - WILDFLY_ADMIN=root
                - WILDFLY_PASSWORD=toor
                # - USER=$USER
        restart: always
        volumes:
            - ../src/replicamanager/build:/opt/jboss/wildfly/standalone/deployments
        ports:
            - 8081:8080
            - 9991:9990
        # depends_on:
        #    - datamanager
        # links:
        #    - datamanager


###



### Volumes and networking
volumes: ## TODO read about the differences with the other way of volumes definition
    ds_rabbitmq_home:

